general_settings:
  master_key: "test-key"  # OPENAI_API_KEY로 사용할 값

model_list:
  - model_name: "llama3"  # Agents에 전달할 모델 이름
    litellm_params:
      model: "ollama/llama3"  # Ollama에서 pull한 모델 이름
      api_base: "http://localhost:11434"  # Ollama 기본 주소
      # api_key는 Ollama엔 불필요하지만, 프록시는 키를 요구할 수 있으므로 생략/임의값 허용

server:
  host: "127.0.0.1"
  port: 4000
